### ISSUE TITLE
Code Review feedback 

### ISSUE THREAD

**Issue by halimb** [Ae111n/markdown-previewer#1]
### Tasks

- [x] Implement the suggestions mentioned in these comments https://github.com/Ae111n/markdown-previewer/commit/b0f615cb7261102abbb72ed9c575d83c95034068#diff-1efc5a830806aebf2ecfbdf277c115e4ea90fbd60b9481b0da475d3c61587114R8
- [x] Remove all the unused files (I see the project has some unused files / folders from the initial setup that are not needed. Example: store/ + store/README.md)
- [x] Rename `mdp` to something more meaningful (example: `MarkdownPreviewer` )

For naming in general:

1- it's important to always choose descriptive names and avoid abbreviations:

MyComponent :heavy_check_mark: 
myCom :x: 
mc :x:  

2- Components should be `PascalCase`

3- Variables and functions should be `camelCase`

4- HTML attributes, should be `kebab-case`
